version: "3.8"

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - ./:/app
