version: "3.8"
services:
    nginx:
        image: auddyhub/ecommerce-nginx:latest
        restart: always
        depends_on:
            - frontend
            - backend
        ports:
            - "80:80"

    frontend:
        image: auddyhub/ecommerce-frontend:latest
        env_file:
            - .env

    backend:
        image: auddyhub/ecommerce-backend:latest
        env_file:
            - .env







