version: "3.8"
services:
    nginx:
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        container_name: nginx
        restart: always
        depends_on:
            - frontend
            - backend
        ports:
            - "3000:80"

    frontend:
        build:
            dockerfile: Dockerfile.dev
            context: ./frontend
        container_name: frontend
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - /app/node_modules
            - ./frontend:/app
        env_file:
            - ./frontend/.env

    backend:
        build:
            dockerfile: Dockerfile.dev
            context: ./backend
        container_name: backend
        volumes:
            - ./backend:/app
        env_file:
            - ./backend/.env