version: "3.8"
services:
    nginx:
        image: ${DOCKER_HUB_USERNAME}/ecommerce-nginx:latest
        restart: always
        depends_on:
            - frontend
            - backend
        ports:
            - "3000:80"
        env_file:
            - ./nginx/.env

    frontend:
        image: ${DOCKER_HUB_USERNAME}/ecommerce-frontend:latest
        environment:
            - CHOKIDAR_USEPOLLING=true
        env_file:
            - ./frontend/.env

    backend:
        image: ${DOCKER_HUB_USERNAME}/ecommerce-backend:latest
        env_file:
            - ./backend/.env