version: "3.8"
services:
    nginx:
        build:
            dockerfile: Dockerfile
            context: ./nginx
        container_name: nginx
        restart: always
        depends_on:
            - frontend
            - backend
        ports:
            - "3000:80"

    frontend:
        build:
            dockerfile: Dockerfile
            context: ./frontend
        container_name: frontend
        environment:
            - CHOKIDAR_USEPOLLING=true

    backend:
        build:
            dockerfile: Dockerfile
            context: ./backend
        environment:
            - PORT=1993
            - PGDATABASE=postgres
            - PGUSER=postgres
            - PGPASSWORD=bOBtibaoin
            - PGHOST=deno-ecommerce.cqpn8yg5ot2b.ap-southeast-1.rds.amazonaws.com
            - PGPORT=5432
            - PGAPPNAME=ecommerce
            - TK_REFRESH_KEY=BIapnit%3ln[a^3biU
            - TK_ACCESS_KEY=bitIbpb[7enobiUbAur
            - TK_NAME=ast
            - SENDGRID_API_ENDPOINT=https://api.sendgrid.com/v3/mail/send
            - SENDGRID_API_KEY=SG.MlMTgHahRT25PkYK_Rmw5s3cRG1Bru4evs40ZXuueH8nymxaKH4Jgb7VgvhGtKA
            - CLOUDINARY_API_KEY=853656979469817
            - CLOUDINARY_API_SECRET=O5XchODkpC2oEbhvmiRxqMLPC4c
            - CLOUDINARY_BASE_URL=https://api.cloudinary.com/v1_1/aut-media/image
            - STRIPE_SECRET_KEY=sk_test_51HwlOcE928BzfJPTLBvpxGf1PStPjM1DJNd6obvOads1zlC9b3s0bbE5JMpbaisVtSyVWqxfLsXlxvUgW3op3DWa00PxHTBbKd
            - STRIPE_CUSTOMERS_URL=https://api.stripe.com/v1/customers
            - DOCKER_HUB_USERNAME=auddyhub

