version: "3.8"
services:
    nginx:
        env_file:
            - .env
        image: ${DOCKER_HUB_USERNAME}/ecommerce-nginx:latest
        restart: always
        depends_on:
            - frontend
            - backend
        ports:
            - "80:80"

    frontend:
        env_file:
            - .env
        image: ${DOCKER_HUB_USERNAME}/ecommerce-frontend:latest

    backend:
        env_file:
            - .env
        image: ${DOCKER_HUB_USERNAME}/ecommerce-backend:latest







