version: "3.8"
services:
    frontend:
        image: ${DOCKER_HUB_USERNAME}/ecommerce-frontend:latest
        volumes:
            - /app/node_modules
            - ./frontend:/app
        container_name: frontend

    backend:
        image: ${DOCKER_HUB_USERNAME}/ecommerce-backend:latest
        volumes:
            - ./backend:/app
        container_name: backend

    nginx:
        image: ${DOCKER_HUB_USERNAME}/ecommerce-nginx:latest
        restart: always
        depends_on:
            - frontend
            - backend
        ports:
            - "80:80"