version: "3.8"
services:
    nginx:
        image: ${DOCKER_HUB_USERNAME}/ecommerce-nginx:latest
        restart: always
        depends_on:
            - frontend
            - backend
        ports:
            - "80:80"

    frontend:
        image: ${DOCKER_HUB_USERNAME}/ecommerce-frontend:latest

    backend:
        image: ${DOCKER_HUB_USERNAME}/ecommerce-backend:latest