version: '3.8'

services:
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "1993:1993"
        volumes:
            - ./:/app
        env_file:
            - ./.env